use antelope::api::client::APIClient;
use antelope::api::default_provider::DefaultProvider;
use antelope::chain::abi::ABI;
use antelope::chain::checksum::Checksum256;
use std::path::Path;
use wharfkit_common::Chains;

use crate::ident::{camel_ident, check_no_collisions, snake_ident};
use crate::CodegenError;

#[derive(Debug, Clone)]
pub struct ResolvedChain {
    pub endpoint: String,
    pub id: String,
    pub label: String,
    pub short_name: String,
}

pub fn resolve_chain(chain_or_url: &str) -> ResolvedChain {
    fn from_definition(
        def: wharfkit_common::ChainDefinition,
        short_name: &str,
        label: &str,
    ) -> ResolvedChain {
        ResolvedChain {
            endpoint: def.url().to_string(),
            id: def.id().as_string(),
            label: label.to_string(),
            short_name: short_name.to_string(),
        }
    }

    match chain_or_url {
        "jungle4" => from_definition(Chains::jungle4(), "jungle4", "Jungle 4 Test Network"),
        "eos" => from_definition(Chains::eos(), "eos", "EOS Mainnet"),
        "wax" => from_definition(Chains::wax(), "wax", "WAX Mainnet"),
        "telos" => from_definition(Chains::telos(), "telos", "Telos Mainnet"),
        other => ResolvedChain {
            endpoint: other.to_string(),
            id: String::new(),
            label: format!("Custom endpoint: {other}"),
            short_name: other.to_string(),
        },
    }
}

pub async fn fetch_abi(
    chain: &ResolvedChain,
    account: &str,
) -> Result<(ABI, String), CodegenError> {
    let client = APIClient::<DefaultProvider>::default_provider(chain.endpoint.clone(), None)
        .map_err(|e| CodegenError::NetworkFetch(format!("APIClient init: {e}")))?;
    let response = client
        .v1_chain
        .get_abi(account.to_string())
        .await
        .map_err(|e| CodegenError::NetworkFetch(format!("get_abi({account}): {e:?}")))?;
    let abi = response.abi;

    let abi_bytes = serde_json::to_vec(&abi)?;
    let abi_hash = Checksum256::hash(abi_bytes).as_string();

    Ok((abi, abi_hash))
}

pub struct EmitContext<'a> {
    pub abi: &'a ABI,
    pub chain: &'a ResolvedChain,
    pub account: &'a str,
    pub abi_hash: &'a str,
    pub tool_version: &'a str,
}

pub fn emit_header(ctx: &EmitContext) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "//! @generated by wharfkit-cli v{} — do not edit by hand.\n",
        ctx.tool_version
    ));
    s.push_str("//!\n");
    s.push_str(&format!("//! Contract: {}\n", ctx.account));
    s.push_str(&format!(
        "//! Chain:    {} ({})\n",
        ctx.chain.label, ctx.chain.id
    ));
    s.push_str(&format!("//! ABI hash: {}\n", ctx.abi_hash));
    s.push_str("//!\n");
    s.push_str("//! Regenerate:\n");
    s.push_str(&format!(
        "//!   wharfkit-cli codegen --chain {} --account {} --out <path>\n",
        ctx.chain.short_name, ctx.account
    ));
    s.push('\n');
    s.push_str("use antelope::chain::abi::ABI;\n");
    s.push_str("use antelope::chain::action::{Action, PermissionLevel};\n");
    s.push_str("use antelope::chain::asset::{Asset, Symbol};\n");
    s.push_str("use antelope::chain::name::{static_str_to_name, Name};\n");
    s.push_str("use antelope::serializer::{Decoder, Encoder, Packer};\n");
    let has_variants = !ctx.abi.variants.is_empty();
    let has_structs = !ctx.abi.structs.is_empty();
    if has_variants && has_structs {
        s.push_str("use antelope::{EnumPacker, StructPacker};\n");
    } else if has_variants {
        s.push_str("use antelope::EnumPacker;\n");
    } else if has_structs {
        s.push_str("use antelope::StructPacker;\n");
    }
    s.push_str("use wharfkit_contract::Table;\n");
    s.push('\n');
    s.push_str(&format!(
        "pub const ACCOUNT: Name = Name {{ n: static_str_to_name(\"{}\") }};\n",
        ctx.account
    ));
    s.push_str(&format!(
        "pub const ABI_HASH: &str = \"{}\";\n",
        ctx.abi_hash
    ));
    s.push('\n');
    s
}

fn wrap_module(name: &str, doc: &str, mut entries: Vec<(String, String)>) -> String {
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut s = String::new();
    s.push_str(&format!("/// {doc}\n"));
    s.push_str(&format!("pub mod {name} {{\n"));
    s.push_str("    use super::*;\n\n");
    for (_, code) in entries {
        s.push_str(&code);
    }
    s.push_str("}\n\n");
    s
}

pub fn emit_types_module(ctx: &EmitContext) -> Result<String, CodegenError> {
    let mut entries: Vec<(String, String)> = Vec::new();

    for s in &ctx.abi.structs {
        let rust_name = camel_ident(&s.name);
        let mut code = String::new();
        code.push_str(&format!("    /// ABI struct `{}`.\n", s.name));
        code.push_str("    #[derive(StructPacker, Default, Clone, Debug)]\n");
        code.push_str(&format!("    pub struct {rust_name} {{\n"));
        for field in &s.fields {
            let field_ident = snake_ident(&field.name);
            let rust_type = abi_type_to_rust_type(&field.r#type)?;
            code.push_str(&format!("        pub {field_ident}: {rust_type},\n"));
        }
        code.push_str("    }\n\n");
        entries.push((rust_name, code));
    }

    for v in &ctx.abi.variants {
        let rust_name = camel_ident(&v.name);
        let mut code = String::new();
        code.push_str(&format!("    /// ABI variant `{}`.\n", v.name));
        code.push_str("    #[derive(EnumPacker, Clone, Debug)]\n");
        code.push_str(&format!("    pub enum {rust_name} {{\n"));
        for inner_type in &v.types {
            let variant_name = camel_ident(inner_type);
            let rust_type = abi_type_to_rust_type(inner_type)?;
            code.push_str(&format!("        {variant_name}({rust_type}),\n"));
        }
        code.push_str("    }\n\n");
        entries.push((rust_name, code));
    }

    Ok(wrap_module(
        "types",
        "ABI types defined by this contract.",
        entries,
    ))
}

// Mirrors the private `is_builtin_type` in antelope-client's `abi.rs`;
// drift surfaces via `CodegenError::MissingBuiltin`.
fn is_abi_builtin(name: &str) -> bool {
    matches!(
        name,
        "bool"
            | "int8"
            | "uint8"
            | "int16"
            | "uint16"
            | "int32"
            | "uint32"
            | "int64"
            | "uint64"
            | "int128"
            | "uint128"
            | "varint32"
            | "varuint32"
            | "float32"
            | "float64"
            | "float128"
            | "bytes"
            | "string"
            | "time_point"
            | "time_point_sec"
            | "block_timestamp_type"
            | "name"
            | "asset"
            | "symbol"
            | "symbol_code"
            | "checksum160"
            | "checksum256"
            | "checksum512"
            | "public_key"
            | "signature"
            | "extended_asset"
    )
}

fn abi_type_to_rust_type(abi_type: &str) -> Result<String, CodegenError> {
    if let Some(inner) = abi_type.strip_suffix('?') {
        return Ok(format!("Option<{}>", abi_type_to_rust_type(inner)?));
    }
    if let Some(inner) = abi_type.strip_suffix("[]") {
        return Ok(format!("Vec<{}>", abi_type_to_rust_type(inner)?));
    }
    if let Some(inner) = abi_type.strip_suffix('$') {
        return Ok(format!("Option<{}>", abi_type_to_rust_type(inner)?));
    }
    let mapped = match abi_type {
        "bool" => "bool",
        "int8" => "i8",
        "uint8" => "u8",
        "int16" => "i16",
        "uint16" => "u16",
        "int32" => "i32",
        "uint32" => "u32",
        "int64" => "i64",
        "uint64" => "u64",
        "int128" => "i128",
        "uint128" => "u128",
        "float32" => "f32",
        "float64" => "f64",
        "float128" => "antelope::serializer::packer::Float128",
        "string" => "String",
        "bytes" => "Vec<u8>",
        "name" => "Name",
        "asset" => "Asset",
        "symbol" => "Symbol",
        "symbol_code" => "antelope::chain::asset::SymbolCode",
        "extended_asset" => "antelope::chain::asset::ExtendedAsset",
        "checksum160" => "antelope::chain::checksum::Checksum160",
        "checksum256" => "antelope::chain::checksum::Checksum256",
        "checksum512" => "antelope::chain::checksum::Checksum512",
        "public_key" => "antelope::chain::public_key::PublicKey",
        "signature" => "antelope::chain::signature::Signature",
        "time_point" => "antelope::chain::time::TimePoint",
        "time_point_sec" => "antelope::chain::time::TimePointSec",
        "block_timestamp_type" => "antelope::chain::time::BlockTimestamp",
        "varuint32" => "antelope::chain::varint::VarUint32",
        "varint32" => "antelope::chain::varint::VarInt32",
        other => {
            if is_abi_builtin(other) {
                return Err(CodegenError::MissingBuiltin(other.to_string()));
            }
            return Ok(camel_ident(other));
        }
    };
    Ok(mapped.to_string())
}

pub fn emit_actions_module(ctx: &EmitContext) -> Result<String, CodegenError> {
    let mut entries: Vec<(String, String)> = Vec::new();

    for action in &ctx.abi.actions {
        let action_name_str = action.name.as_string();
        let fn_ident = snake_ident(&action_name_str);
        let arg_struct = camel_ident(&action.r#type);
        let Some(arg_struct_def) = ctx.abi.structs.iter().find(|s| s.name == action.r#type) else {
            let mut code = String::new();
            code.push_str(&format!("    /// Build a `{}` action.\n", action_name_str));
            code.push_str(&format!(
                "    pub fn {fn_ident}(authorization: PermissionLevel, data: types::{arg_struct}) -> Action {{\n"
            ));
            code.push_str(&format!(
                "        Action::new(super::ACCOUNT, Name::new_from_str(\"{}\"), authorization, data)\n",
                action_name_str
            ));
            code.push_str("    }\n\n");
            entries.push((fn_ident, code));
            continue;
        };

        let mut code = String::new();
        code.push_str(&format!("    /// Build a `{}` action.\n", action_name_str));
        let mut params: Vec<String> = vec!["authorization: PermissionLevel".to_string()];
        for f in &arg_struct_def.fields {
            let field_ident = snake_ident(&f.name);
            let rust_type = abi_type_to_rust_type(&f.r#type)?;
            let typed = if rust_type == "String" {
                "impl Into<String>".to_string()
            } else {
                rust_type
            };
            params.push(format!("{field_ident}: {typed}"));
        }
        code.push_str(&format!(
            "    pub fn {fn_ident}({}) -> Action {{\n",
            params.join(", ")
        ));
        code.push_str(&format!("        let data = types::{arg_struct} {{\n"));
        for field in &arg_struct_def.fields {
            let field_ident = snake_ident(&field.name);
            let rust_type = abi_type_to_rust_type(&field.r#type)?;
            if rust_type == "String" {
                code.push_str(&format!(
                    "            {field_ident}: {field_ident}.into(),\n"
                ));
            } else {
                code.push_str(&format!("            {field_ident},\n"));
            }
        }
        code.push_str("        };\n");
        code.push_str(&format!(
            "        Action::new(super::ACCOUNT, Name::new_from_str(\"{}\"), authorization, data)\n",
            action_name_str
        ));
        code.push_str("    }\n\n");
        entries.push((fn_ident, code));
    }

    Ok(wrap_module(
        "actions",
        "Action factories for this contract.",
        entries,
    ))
}

pub fn emit_tables_module(ctx: &EmitContext) -> Result<String, CodegenError> {
    let mut entries: Vec<(String, String)> = Vec::new();

    for table in &ctx.abi.tables {
        let table_name_str = table.name.as_string();
        let fn_ident = snake_ident(&table_name_str);
        let row_type = camel_ident(&table.r#type);
        let mut code = String::new();
        code.push_str(&format!("    /// Access the `{}` table.\n", table_name_str));
        code.push_str(&format!(
            "    pub fn {fn_ident}(scope: Name) -> Table<types::{row_type}> {{\n"
        ));
        code.push_str(&format!(
            "        Table::new(super::ACCOUNT, Name::new_from_str(\"{}\"), scope)\n",
            table_name_str
        ));
        code.push_str("    }\n\n");
        entries.push((fn_ident, code));
    }

    Ok(wrap_module(
        "tables",
        "Typed table accessors for this contract.",
        entries,
    ))
}

pub fn emit_abi_helpers(ctx: &EmitContext) -> Result<String, CodegenError> {
    let json_bytes = serde_json::to_vec(ctx.abi)?;
    let hex_str = hex::encode(&json_bytes);

    let mut s = String::new();
    s.push_str("/// The packed ABI bytes (JSON-encoded) for runtime decoding paths.\n");
    s.push_str("pub fn abi_blob() -> &'static [u8] {\n");
    s.push_str(&format!("    const HEX: &str = \"{hex_str}\";\n"));
    s.push_str("    static BYTES: std::sync::OnceLock<Vec<u8>> = std::sync::OnceLock::new();\n");
    s.push_str("    BYTES.get_or_init(|| hex::decode(HEX).expect(\"valid hex\")).as_slice()\n");
    s.push_str("}\n\n");
    s.push_str("/// Parse the contract's ABI.\n");
    s.push_str("pub fn abi() -> ABI {\n");
    s.push_str("    serde_json::from_slice(abi_blob()).expect(\"valid ABI JSON\")\n");
    s.push_str("}\n");
    Ok(s)
}

const TOOL_VERSION: &str = env!("CARGO_PKG_VERSION");

fn check_ident_collisions(abi: &ABI) -> Result<(), CodegenError> {
    let type_names: Vec<String> = abi
        .structs
        .iter()
        .map(|s| s.name.clone())
        .chain(abi.variants.iter().map(|v| v.name.clone()))
        .collect();
    check_no_collisions(type_names, camel_ident).map_err(CodegenError::IdentCollision)?;

    let action_names: Vec<String> = abi.actions.iter().map(|a| a.name.as_string()).collect();
    check_no_collisions(action_names, snake_ident).map_err(CodegenError::IdentCollision)?;

    let table_names: Vec<String> = abi.tables.iter().map(|t| t.name.as_string()).collect();
    check_no_collisions(table_names, snake_ident).map_err(CodegenError::IdentCollision)?;

    Ok(())
}

pub async fn run(chain_arg: &str, account: &str, out: &Path) -> Result<(), CodegenError> {
    let chain = resolve_chain(chain_arg);
    let (abi, abi_hash) = fetch_abi(&chain, account).await?;
    let ctx = EmitContext {
        abi: &abi,
        chain: &chain,
        account,
        abi_hash: &abi_hash,
        tool_version: TOOL_VERSION,
    };

    check_ident_collisions(ctx.abi)?;

    let mut source = String::new();
    source.push_str(&emit_header(&ctx));
    source.push_str(&emit_types_module(&ctx)?);
    source.push_str(&emit_actions_module(&ctx)?);
    source.push_str(&emit_tables_module(&ctx)?);
    source.push_str(&emit_abi_helpers(&ctx)?);

    let formatted = rustfmt_string(&source)?;

    if let Some(parent) = out.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(out, formatted)?;
    println!("Generated: {}", out.display());
    Ok(())
}

fn rustfmt_string(source: &str) -> Result<String, CodegenError> {
    use std::io::Write;
    use std::process::{Command, Stdio};
    let mut child = Command::new("rustfmt")
        .arg("--edition")
        .arg("2021")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| CodegenError::Rustfmt(format!("spawn rustfmt — is it installed? {e}")))?;
    child
        .stdin
        .as_mut()
        .ok_or_else(|| CodegenError::Rustfmt("rustfmt stdin not captured".to_string()))?
        .write_all(source.as_bytes())?;
    let output = child.wait_with_output()?;
    if !output.status.success() {
        return Err(CodegenError::Rustfmt(
            String::from_utf8_lossy(&output.stderr).into_owned(),
        ));
    }
    String::from_utf8(output.stdout)
        .map_err(|e| CodegenError::Rustfmt(format!("rustfmt produced non-UTF-8 output: {e}")))
}

#[cfg(test)]
mod resolve_chain_tests {
    use super::*;

    #[test]
    fn resolve_jungle4_via_wharfkit_common() {
        let c = resolve_chain("jungle4");
        assert_eq!(c.label, "Jungle 4 Test Network");
        assert!(c.endpoint.contains("jungle4"));
        assert_eq!(c.id.len(), 64);
        assert_eq!(c.short_name, "jungle4");
    }

    #[test]
    fn resolve_unknown_returns_input_as_endpoint() {
        let c = resolve_chain("https://my.custom.node");
        assert_eq!(c.endpoint, "https://my.custom.node");
        assert!(c.id.is_empty());
        assert_eq!(c.short_name, "https://my.custom.node");
    }

    #[test]
    fn resolve_eos_wax_telos() {
        for (short, expected_label_fragment) in [("eos", "EOS"), ("wax", "WAX"), ("telos", "Telos")]
        {
            let c = resolve_chain(short);
            assert!(
                c.label.contains(expected_label_fragment),
                "label for {short} should contain {expected_label_fragment}, got {}",
                c.label
            );
            assert_eq!(c.short_name, short);
            assert_eq!(c.id.len(), 64);
        }
    }
}

#[cfg(test)]
mod emit_header_tests {
    use super::*;

    fn fixture_ctx<'a>(abi: &'a ABI, chain: &'a ResolvedChain) -> EmitContext<'a> {
        EmitContext {
            abi,
            chain,
            account: "eosio.token",
            abi_hash: "deadbeef",
            tool_version: "0.1.0",
        }
    }

    #[test]
    fn header_includes_required_fields() {
        let abi: ABI = serde_json::from_str(r#"{"version":"eosio::abi/1.2","types":[],"structs":[],"actions":[],"tables":[],"variants":[]}"#).unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = fixture_ctx(&abi, &chain);
        let out = emit_header(&ctx);
        assert!(out.contains("@generated by wharfkit-cli v0.1.0"));
        assert!(out.contains("Contract: eosio.token"));
        assert!(out.contains("Chain:    Jungle 4 Test Network"));
        assert!(out.contains("ABI hash: deadbeef"));
        assert!(out.contains("wharfkit-cli codegen --chain jungle4 --account eosio.token"));
        assert!(out.contains("pub const ACCOUNT"));
        assert!(out.contains("pub const ABI_HASH: &str = \"deadbeef\";"));
    }

    #[test]
    fn header_does_not_include_timestamp() {
        let abi: ABI = serde_json::from_str(r#"{"version":"eosio::abi/1.2","types":[],"structs":[],"actions":[],"tables":[],"variants":[]}"#).unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = fixture_ctx(&abi, &chain);
        let out1 = emit_header(&ctx);
        let out2 = emit_header(&ctx);
        assert_eq!(out1, out2);
        assert!(!out1.contains("2026"));
    }

    #[test]
    fn header_imports_serializer_encoder_decoder() {
        let abi: ABI = serde_json::from_str(r#"{"version":"eosio::abi/1.2","types":[],"structs":[],"actions":[],"tables":[],"variants":[]}"#).unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = fixture_ctx(&abi, &chain);
        let out = emit_header(&ctx);
        assert!(
            out.contains("Encoder") && out.contains("Decoder"),
            "header must import Encoder and Decoder for StructPacker / EnumPacker; got:\n{out}"
        );
    }

    #[test]
    fn header_does_not_import_unused_enum_packer_when_no_variants() {
        let abi: ABI = serde_json::from_str(r#"{"version":"eosio::abi/1.2","types":[],"structs":[{"name":"x","base":"","fields":[]}],"actions":[],"tables":[],"variants":[]}"#).unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = fixture_ctx(&abi, &chain);
        let out = emit_header(&ctx);
        assert!(
            !out.contains("EnumPacker"),
            "header must not import EnumPacker when the ABI has no variants; got:\n{out}"
        );
        assert!(
            out.contains("StructPacker"),
            "header still needs StructPacker for the struct in this fixture; got:\n{out}"
        );
    }

    #[test]
    fn header_imports_enum_packer_when_variants_present() {
        let abi: ABI = serde_json::from_str(r#"{"version":"eosio::abi/1.2","types":[],"structs":[],"actions":[],"tables":[],"variants":[{"name":"v","types":["int32"]}]}"#).unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = fixture_ctx(&abi, &chain);
        let out = emit_header(&ctx);
        assert!(
            out.contains("EnumPacker"),
            "header must import EnumPacker when the ABI has variants; got:\n{out}"
        );
    }
}

#[cfg(test)]
mod emit_types_tests {
    use super::*;

    #[test]
    fn emit_types_alphabetical_order() {
        let abi: ABI = serde_json::from_str(
            r#"{
            "version":"eosio::abi/1.2","types":[],
            "structs":[
                {"name":"transfer","base":"","fields":[{"name":"from","type":"name"}]},
                {"name":"account","base":"","fields":[{"name":"balance","type":"asset"}]}
            ],
            "actions":[],"tables":[],"variants":[]
        }"#,
        )
        .unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = EmitContext {
            abi: &abi,
            chain: &chain,
            account: "eosio.token",
            abi_hash: "x",
            tool_version: "0.1.0",
        };
        let out = emit_types_module(&ctx).unwrap();
        let account_pos = out.find("pub struct Account").expect("Account emitted");
        let transfer_pos = out.find("pub struct Transfer").expect("Transfer emitted");
        assert!(
            account_pos < transfer_pos,
            "Account must come before Transfer alphabetically"
        );
    }

    #[test]
    fn emit_types_includes_variants() {
        let abi: ABI = serde_json::from_str(
            r#"{
            "version":"eosio::abi/1.2","types":[],
            "structs":[],
            "actions":[],"tables":[],
            "variants":[{"name":"v1","types":["int32","string"]}]
        }"#,
        )
        .unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = EmitContext {
            abi: &abi,
            chain: &chain,
            account: "x",
            abi_hash: "x",
            tool_version: "0.1.0",
        };
        let out = emit_types_module(&ctx).unwrap();
        assert!(out.contains("pub enum V1"));
        assert!(out.contains("Int32(i32)"));
        assert!(out.contains("String(String)"));
    }

    #[test]
    fn emit_types_variant_derives_enumpacker() {
        let abi: ABI = serde_json::from_str(
            r#"{
            "version":"eosio::abi/1.2","types":[],
            "structs":[],
            "actions":[],"tables":[],
            "variants":[{"name":"v1","types":["int32","string"]}]
        }"#,
        )
        .unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = EmitContext {
            abi: &abi,
            chain: &chain,
            account: "x",
            abi_hash: "x",
            tool_version: "0.1.0",
        };
        let out = emit_types_module(&ctx).unwrap();
        assert!(
            out.contains("#[derive(EnumPacker, Clone, Debug)]"),
            "variant must derive EnumPacker; got:\n{out}"
        );
    }
}

#[cfg(test)]
mod abi_type_tests {
    use super::*;

    #[test]
    fn builtin_int128_uint128() {
        assert_eq!(abi_type_to_rust_type("int128").unwrap(), "i128");
        assert_eq!(abi_type_to_rust_type("uint128").unwrap(), "u128");
    }

    #[test]
    fn builtin_float128_maps_to_antelope_struct() {
        assert_eq!(
            abi_type_to_rust_type("float128").unwrap(),
            "antelope::serializer::packer::Float128"
        );
    }

    #[test]
    fn builtin_checksum160_512() {
        assert_eq!(
            abi_type_to_rust_type("checksum160").unwrap(),
            "antelope::chain::checksum::Checksum160"
        );
        assert_eq!(
            abi_type_to_rust_type("checksum512").unwrap(),
            "antelope::chain::checksum::Checksum512"
        );
    }

    #[test]
    fn builtin_symbol_code_and_extended_asset() {
        assert_eq!(
            abi_type_to_rust_type("symbol_code").unwrap(),
            "antelope::chain::asset::SymbolCode"
        );
        assert_eq!(
            abi_type_to_rust_type("extended_asset").unwrap(),
            "antelope::chain::asset::ExtendedAsset"
        );
    }

    #[test]
    fn unknown_builtin_returns_missing_builtin_error() {
        assert_eq!(abi_type_to_rust_type("my_struct").unwrap(), "MyStruct");
    }

    #[test]
    fn nested_int128_through_option_and_vec() {
        assert_eq!(abi_type_to_rust_type("int128?").unwrap(), "Option<i128>");
        assert_eq!(abi_type_to_rust_type("uint128[]").unwrap(), "Vec<u128>");
    }
}

#[cfg(test)]
mod emit_actions_tests {
    use super::*;

    #[test]
    fn emit_actions_factory_signature() {
        let abi: ABI = serde_json::from_str(
            r#"{
            "version":"eosio::abi/1.2","types":[],
            "structs":[{
                "name":"transfer","base":"",
                "fields":[
                    {"name":"from","type":"name"},
                    {"name":"to","type":"name"},
                    {"name":"quantity","type":"asset"},
                    {"name":"memo","type":"string"}
                ]
            }],
            "actions":[{"name":"transfer","type":"transfer","ricardian_contract":""}],
            "tables":[],"variants":[]
        }"#,
        )
        .unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = EmitContext {
            abi: &abi,
            chain: &chain,
            account: "eosio.token",
            abi_hash: "x",
            tool_version: "0.1.0",
        };
        let out = emit_actions_module(&ctx).unwrap();
        assert!(out.contains("pub fn transfer("));
        assert!(out.contains("from: Name"));
        assert!(out.contains("to: Name"));
        assert!(out.contains("quantity: Asset"));
        assert!(out.contains("memo: impl Into<String>"));
        assert!(out.contains("Name::new_from_str(\"transfer\")"));
    }
}

#[cfg(test)]
mod emit_tables_tests {
    use super::*;

    #[test]
    fn emit_tables_accessor_signature() {
        let abi: ABI = serde_json::from_str(
            r#"{
            "version":"eosio::abi/1.2","types":[],
            "structs":[{"name":"account","base":"","fields":[{"name":"balance","type":"asset"}]}],
            "actions":[],
            "tables":[{"name":"accounts","type":"account","index_type":"i64","key_names":[],"key_types":[]}],
            "variants":[]
        }"#,
        )
        .unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = EmitContext {
            abi: &abi,
            chain: &chain,
            account: "eosio.token",
            abi_hash: "x",
            tool_version: "0.1.0",
        };
        let out = emit_tables_module(&ctx).unwrap();
        assert!(out.contains("pub fn accounts(scope: Name) -> Table<types::Account>"));
        assert!(out.contains("Name::new_from_str(\"accounts\")"));
    }
}

#[cfg(test)]
mod emit_abi_helpers_tests {
    use super::*;

    #[test]
    fn abi_helpers_emit() {
        let abi: ABI = serde_json::from_str(r#"{"version":"eosio::abi/1.2","types":[],"structs":[],"actions":[],"tables":[],"variants":[]}"#).unwrap();
        let chain = resolve_chain("jungle4");
        let ctx = EmitContext {
            abi: &abi,
            chain: &chain,
            account: "x",
            abi_hash: "x",
            tool_version: "0.1.0",
        };
        let out = emit_abi_helpers(&ctx).unwrap();
        assert!(out.contains("pub fn abi_blob"));
        assert!(out.contains("pub fn abi()"));
    }
}

#[cfg(test)]
mod collision_tests {
    use super::*;

    #[test]
    fn collision_across_two_structs_munges_to_same_ident() {
        let abi: ABI = serde_json::from_str(
            r#"{
            "version":"eosio::abi/1.2","types":[],
            "structs":[
                {"name":"foo_bar","base":"","fields":[]},
                {"name":"foo.bar","base":"","fields":[]}
            ],
            "actions":[],"tables":[],"variants":[]
        }"#,
        )
        .unwrap();
        let result = check_ident_collisions(&abi);
        assert!(
            matches!(result, Err(CodegenError::IdentCollision(_))),
            "expected IdentCollision, got {result:?}"
        );
    }

    #[test]
    fn no_collision_for_disjoint_names() {
        let abi: ABI = serde_json::from_str(
            r#"{
            "version":"eosio::abi/1.2","types":[],
            "structs":[
                {"name":"foo","base":"","fields":[]},
                {"name":"bar","base":"","fields":[]}
            ],
            "actions":[],"tables":[],"variants":[]
        }"#,
        )
        .unwrap();
        assert!(check_ident_collisions(&abi).is_ok());
    }

    #[test]
    fn collision_across_actions() {
        let abi: ABI = serde_json::from_str(
            r#"{
            "version":"eosio::abi/1.2","types":[],
            "structs":[
                {"name":"a","base":"","fields":[]}
            ],
            "actions":[
                {"name":"foo.bar","type":"a","ricardian_contract":""},
                {"name":"foo.bar","type":"a","ricardian_contract":""}
            ],
            "tables":[],"variants":[]
        }"#,
        )
        .unwrap();
        let result = check_ident_collisions(&abi);
        assert!(
            matches!(result, Err(CodegenError::IdentCollision(_))),
            "expected IdentCollision for duplicate action names, got {result:?}"
        );
    }
}
